spring:
  application:
    name: vehicle

  datasource:
    url: jdbc:mysql://localhost:3306/vehicle_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

cloudinary:
  cloud_name: dhdprfqyj
  api_key: 619796154224257
  api_secret: -wkxOB8OdGB6h-d6r07lV0pgaGQ

server:
  port: 8083

profiles:
  active: dev

external:
  vehicle:
    api:
      url: "https://external-api.com/vehicle"
      key: "YOUR_SECRET_API_KEY"

